allowBuilds:
  '@embedded-postgres/windows-x64': true
  '@swc/core': true
  '@tailwindcss/oxide': true
  esbuild: true
  leveldown: true
  protobufjs: true

overrides:
  'tailwindcss>nanoid': 3.3.7
  'express>path-to-regexp': 0.1.13
  lodash: ^4.18.1
  lodash-es: ^4.18.1
